In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df_titanic=pd.read_csv('titanic_train.csv')

In [3]:
df_titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df_titanic.drop('Cabin',axis=1,inplace=True)

In [5]:
df_titanic['Age'].fillna(df_titanic['Age'].mean(),inplace=True)

In [6]:
df_titanic['Embarked'].fillna('S',inplace=True)

In [7]:
df_titanic.drop('Name',axis=1,inplace=True)

In [8]:
df_titanic.Sex.replace(('male','female'),(0,1),inplace=True)
df_titanic.drop('Ticket',axis=1,inplace=True)

In [9]:
df_titanic.Embarked.replace(('S','C','Q'),(0,1,2),inplace=True)

In [10]:
df_titanic.head(1)

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch  Fare  Embarked
0            1         0       3    0  22.0      1      0  7.25         0

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
std_scaling=StandardScaler()

In [13]:
std_scaling.fit(df_titanic.drop(['Survived'],axis=1))

C:\Users\CHATANAYA\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [14]:
scaled_features=std_scaling.transform(df_titanic.drop(['Survived'],axis=1))

C:\Users\CHATANAYA\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  """Entry point for launching an IPython kernel.


In [15]:
scaled_features

array([[-1.73010796,  0.82737724, -0.73769513, ..., -0.47367361,
        -0.50244517, -0.56883712],
       [-1.72622007, -1.56610693,  1.35557354, ..., -0.47367361,
         0.78684529,  1.00518113],
       [-1.72233219,  0.82737724,  1.35557354, ..., -0.47367361,
        -0.48885426, -0.56883712],
       ...,
       [ 1.72233219,  0.82737724,  1.35557354, ...,  2.00893337,
        -0.17626324, -0.56883712],
       [ 1.72622007, -1.56610693, -0.73769513, ..., -0.47367361,
        -0.04438104,  1.00518113],
       [ 1.73010796,  0.82737724, -0.73769513, ..., -0.47367361,
        -0.49237783,  2.57919938]])

In [20]:
df_titanic_std=pd.DataFrame(scaled_features,columns=['PassengerId','Pclass','Sex','Age','SibSp','Parch','Fare','Embarked'])

In [21]:
df_titanic_std.head()

PassengerId    Pclass       Sex       Age     SibSp     Parch      Fare  \
0    -1.730108  0.827377 -0.737695 -0.592481  0.432793 -0.473674 -0.502445   
1    -1.726220 -1.566107  1.355574  0.638789  0.432793 -0.473674  0.786845   
2    -1.722332  0.827377  1.355574 -0.284663 -0.474545 -0.473674 -0.488854   
3    -1.718444 -1.566107  1.355574  0.407926  0.432793 -0.473674  0.420730   
4    -1.714556  0.827377 -0.737695  0.407926 -0.474545 -0.473674 -0.486337   

   Embarked  
0 -0.568837  
1  1.005181  
2 -0.568837  
3 -0.568837  
4 -0.568837

In [22]:
from sklearn.model_selection import train_test_split

In [59]:
X=df_titanic_std.drop('PassengerId',axis=1)
y=df_titanic['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=101)

In [60]:
from sklearn.linear_model import LogisticRegression

In [61]:
log_model=LogisticRegression()

In [62]:
log_model.fit(X_train,y_train)

C:\Users\CHATANAYA\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [63]:
y_pred=log_model.predict(X_test)

In [64]:
from sklearn.metrics import classification_report,confusion_matrix

In [65]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.78      0.88      0.82       154
           1       0.80      0.66      0.72       114

   micro avg       0.78      0.78      0.78       268
   macro avg       0.79      0.77      0.77       268
weighted avg       0.79      0.78      0.78       268

[[135  19]
 [ 39  75]]


In [66]:
from sklearn.svm import SVC
svc_model=SVC()
svc_model.fit(X_train,y_train)
y_pred_svc=svc_model.predict(X_test)

C:\Users\CHATANAYA\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [67]:
print(classification_report(y_test,y_pred_svc))
print(confusion_matrix(y_test,y_pred_svc))

              precision    recall  f1-score   support

           0       0.80      0.93      0.86       154
           1       0.88      0.68      0.77       114

   micro avg       0.82      0.82      0.82       268
   macro avg       0.84      0.81      0.81       268
weighted avg       0.83      0.82      0.82       268

[[143  11]
 [ 36  78]]


In [69]:
from sklearn.ensemble import RandomForestClassifier
randomforest=RandomForestClassifier(n_estimators=200)
randomforest.fit(X_train,y_train)
y_pred=randomforest.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.87      0.84       154
           1       0.80      0.72      0.76       114

   micro avg       0.81      0.81      0.81       268
   macro avg       0.81      0.79      0.80       268
weighted avg       0.81      0.81      0.80       268

